# Generated by Django 4.0.8 on 2023-06-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
