# Generated by Django 4.0.8 on 2023-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_App', '0002_applyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
